# Лабораторная работа 1. Язык Python, основные библиотеки для анализа данных.

ФИО: Копин Борис Александрович

Группа: 

In [1]:
import numpy as np
import pandas as pd
from functools import reduce

## Часть 1: Python

#### 1. Напишите код, который сформирует список всех натуральных чисел, не превосходящих 100, которые делятся на 7 и не делятся на 5. Нельзя использовать циклы — выполните это задание с помощью list comprehension.

In [2]:
[x for x in range(1, 101) if (x%7==0) and (x%5!=0)]

[7, 14, 21, 28, 42, 49, 56, 63, 77, 84, 91, 98]

#### 2. Напишите функцию `sort_tokens(s)`, которая принимает на вход строку, разделяет ее на токены по запятым, сортирует токены с помощью функции `sorted()` и снова соединяет их в одну строку через запятые. Например, для строки `u"ночь,фонарь,улица"` функция должна выдать `u"ночь,улица,фонарь"`. Придумайте несколько входных строк и протестируйте функцию на них.

Обратите внимание, что склеить строки можно с помощью конструкции `'x'.join(...)`. Например:

In [3]:
'! '.join(['i', 'am', 'very', 'excited', ':-)'])

'i! am! very! excited! :-)'

In [4]:
def sort_tokens(s):
    words = s.split(',')
    words = sorted(words)
    return ','.join(words)

str = u"ночь,фонарь,улица"
print(sort_tokens(str))

ночь,улица,фонарь


#### 3. Напишите функцию `remove_duplicates(a)`, которая принимает на вход список и возвращает его же, но без дубликатов и в отсортированном виде. Например, для списка `[u"ночь", u"улица", u"фонарь", u"аптека", u"аптека", u"улица", u"фонарь"]` результат должен быть `[u"аптека", u"ночь", u"улица", u"фонарь", ]`.

Подсказка: обратите внимание на структуру `set`!

In [5]:
def remove_duplicates(a):
    return set(a)
array = [u"ночь", u"улица", u"фонарь", u"аптека", u"аптека", u"улица", u"фонарь"]
print(remove_duplicates(array))

{'ночь', 'улица', 'аптека', 'фонарь'}


#### 4. Напишите функцию `word_counts(texts)`, которая принимает на вход список строк, и печатает пары (слово, число вхождений). Считайте, что слова в текстах могут быть разделены только пробелами. Например, для входа `[u'ночь улица фонарь аптека', u'аптека улица фонарь']` должно быть напечатано
>аптека 2

>улица 2

>фонарь 2

>ночь 1

Подсказки:

Чтобы разбить каждый из текстов на слова, воспользуйтесь функцией `map`, которая применяет заданную функцию к каждому элементу списка. Например, если бы нужно было каждый из текстов привести к нижнему регистру, то команда выглядела бы так:

In [6]:
list(map(lambda x: x.lower(), ["abCDefg", "HIjkL"]))

['abcdefg', 'hijkl']

После первого шага вы получите список, состоящий из списков слов. Чтобы объединить их в один список слов, воспользуйтесь функцией `reduce`. Например, просуммировать числа из списка с ее помощью можно так:



In [7]:
reduce(lambda x, y: x + y, [1, 2, 3, 4, 5])

15

Для подсчета количества вхождений слов воспользуйтесь структурой `defaultdict` из модуля `collections`. В отличие от обычного `dict`, она не генерирует ошибку при обращении к несуществущему ключу, а создает новую запись, инициализируемую нулевым значением. Например:

In [8]:
from collections import defaultdict
d = defaultdict(int)
print(d)
d['abc'] += 1
print(d)
d['xxx']
print(d)

defaultdict(<class 'int'>, {})
defaultdict(<class 'int'>, {'abc': 1})
defaultdict(<class 'int'>, {'xxx': 0, 'abc': 1})


In [9]:
def word_counts(texts):
    bag = defaultdict(int)
    
    splited = map(lambda x: x.split(' '), texts)
    reduced = reduce(lambda x, y: x + y, splited)
    
    for word in reduced:
        bag[word]+=1
        
    return bag

str = [u'ночь улица фонарь аптека', u'аптека улица фонарь']
print(word_counts(str))

defaultdict(<class 'int'>, {'ночь': 1, 'аптека': 2, 'фонарь': 2, 'улица': 2})


#### 5. (бонусное задание) Скачайте английский перевод "Преступления и наказания". Найдите 20 самых популярных слов и 20 слов, которые встречаются только один раз.

Приведите текст к нижнему регистру. Разделите текст на слова, считая разделителями все, кроме букв. Обратите внимание на функцию `split` из модуля `re`.

Не забудьте удалить пустые слова:
```
words = filter(lambda x: len(x) > 0, words)
```

In [10]:
from urllib.request import urlopen
url = "http://www.gutenberg.org/files/2554/2554.txt"
response = urlopen(url)
raw_text = response.read().decode('utf8')

In [11]:
raw_text[1000:1100]

'r five\r\nchildren in only two rooms. The father and mother spent their evenings\r\nin reading aloud to '

In [12]:
import string
import re
import operator

raw_text = raw_text.lower()
delimiters = set(raw_text) - set(string.ascii_lowercase)

words = re.split('\W+', raw_text)
words = filter(lambda x: len(x) > 0, words)

counted_words = word_counts([" ".join(words)])
sorted_words = sorted(counted_words.items(), key=operator.itemgetter(1), reverse=True)

twenty_of_most_popular_words = sorted_words[:20]
twenty_of_once_occured_words = [x for x in sorted_words if x[1] == 1][:20]

print(twenty_of_most_popular_words)
print(twenty_of_once_occured_words)

[('the', 7995), ('and', 7042), ('to', 5493), ('he', 4892), ('a', 4665), ('i', 4402), ('you', 4114), ('of', 3926), ('it', 3460), ('that', 3294), ('in', 3250), ('was', 2826), ('his', 2114), ('at', 2082), ('her', 1828), ('but', 1801), ('not', 1774), ('s', 1765), ('with', 1757), ('she', 1692)]
[('crudest', 1), ('daring_', 1), ('clashed', 1), ('bitten', 1), ('scrubs', 1), ('vindictively', 1), ('tiniest', 1), ('quenching', 1), ('slay', 1), ('gulps', 1), ('mouthed', 1), ('fawning', 1), ('lagging', 1), ('afresh', 1), ('modest', 1), ('experiments', 1), ('post_', 1), ('impertinent', 1), ('idea_', 1), ('nou', 1)]


## Часть 2: NumPy и SciPy

#### 1. Повторите 1000 раз следующий эксперимент: сгенерируйте две матрицы размера $10 \times 10$ из стандартного нормального распределения, перемножьте их (как матрицы) и найдите максимальный элемент. Какое среднее значение по экспериментам у максимальных элементов? 95-процентная квантиль?

Для вычисления квантили воспользуйтесь функцией `np.percentile`

In [13]:
iterations = 1000
alpha = 95

maximums = []
for x in range(iterations):
    matrix1 = np.random.standard_normal(size=(10,10))
    matrix2 = np.random.standard_normal(size=(10,10))
    maximums.append(np.max(np.dot(matrix1, matrix2)))
    
print(np.mean(maximums))
print(np.percentile(maximums, alpha))

8.45467399642
11.9031934523


#### 2. Сгенерируйте 1000 чисел из распределения Пуассона с параметром $\lambda = 5$. Сформируйте массив, в котором в i-м элементе будет записано количество сгенерированных чисел, равных i.

Обратите внимание на функцию `np.bincount`

In [14]:
n = np.random.poisson(5, 1000)

counts = np.bincount(n)
indexes = np.nonzero(counts)[0]
bag = list(zip(range(counts.size), counts))

print(bag)
print(counts)


[(0, 4), (1, 36), (2, 81), (3, 149), (4, 178), (5, 159), (6, 158), (7, 110), (8, 56), (9, 36), (10, 18), (11, 11), (12, 4)]
[  4  36  81 149 178 159 158 110  56  36  18  11   4]


#### 3. Реализуйте функцию, которая принимает на вход numpy-массив целых чисел `a`, и генерирует массив, в котором число `i` встречается `a[i]` раз. Протестируйте на результате из прошлого задания.

Обратите внимание на функцию `np.repeat`

In [15]:
def repeater(a):
    return np.repeat(a, a)

print(repeater(counts))

[  4   4   4   4  36  36  36  36  36  36  36  36  36  36  36  36  36  36
  36  36  36  36  36  36  36  36  36  36  36  36  36  36  36  36  36  36
  36  36  36  36  81  81  81  81  81  81  81  81  81  81  81  81  81  81
  81  81  81  81  81  81  81  81  81  81  81  81  81  81  81  81  81  81
  81  81  81  81  81  81  81  81  81  81  81  81  81  81  81  81  81  81
  81  81  81  81  81  81  81  81  81  81  81  81  81  81  81  81  81  81
  81  81  81  81  81  81  81  81  81  81  81  81  81 149 149 149 149 149
 149 149 149 149 149 149 149 149 149 149 149 149 149 149 149 149 149 149
 149 149 149 149 149 149 149 149 149 149 149 149 149 149 149 149 149 149
 149 149 149 149 149 149 149 149 149 149 149 149 149 149 149 149 149 149
 149 149 149 149 149 149 149 149 149 149 149 149 149 149 149 149 149 149
 149 149 149 149 149 149 149 149 149 149 149 149 149 149 149 149 149 149
 149 149 149 149 149 149 149 149 149 149 149 149 149 149 149 149 149 149
 149 149 149 149 149 149 149 149 149 149 149 149 14

#### 4. Напишите функцию `scale(X)`, которая принимает на вход матрицу и масштабирует каждый ее столбец (вычитает среднее и делит на стандартное отклонение). Убедитесь, что в функции не будет происходить деления на ноль. Протестируйте на каких-нибудь данных.

In [16]:
def scale(x):
    for j in range(x.shape[1]):
        column = x[:,j]
        std = np.std(column)
        if std != 0:
            x[:,j] = (column - np.mean(column))/np.std(column)
    return x

myarr = np.random.binomial(100, 0.7, size=(10,10))

print(myarr)
myarr = scale(myarr)
print(myarr)


[[68 73 71 70 77 70 69 69 68 73]
 [68 70 66 69 61 76 64 76 74 72]
 [76 75 66 62 67 72 77 77 69 77]
 [63 69 69 74 63 71 69 68 66 66]
 [74 69 66 63 69 62 66 65 68 70]
 [73 72 69 76 70 71 73 67 68 70]
 [75 72 66 68 66 79 67 71 75 63]
 [66 65 70 73 73 67 73 78 66 71]
 [72 62 72 60 70 68 70 67 68 67]
 [78 72 70 75 64 75 71 71 69 71]]
[[ 0  0  1  0  1  0  0  0  0  0]
 [ 0  0 -1  0 -1  1 -1  1  1  0]
 [ 1  1 -1 -1  0  0  1  1  0  1]
 [-1  0  0  0 -1  0  0  0 -1 -1]
 [ 0  0 -1 -1  0 -1 -1 -1  0  0]
 [ 0  0  0  1  0  0  0  0  0  0]
 [ 0  0 -1  0  0  1  0  0  2 -1]
 [-1 -1  0  0  1  0  0  1 -1  0]
 [ 0 -2  1 -1  0  0  0  0  0  0]
 [ 1  0  0  1  0  0  0  0  0  0]]


#### 5. Сгенерируйте матрицу с элементами из нормального распределения $\mathcal{N}(10, 1)$. Найдите ее:
- определитель
- след
- наименьший и наибольший элементы
- спектральную норму
- норму Фробениуса
- собственные числа
- обратную матрицу

In [17]:
m = np.random.normal(10, 1, size=(10, 10))

print(np.linalg.det(m))
print(np.trace(m))
print(np.amin(m), np.amax(m))
# print(np.linalg.norm(m, 'ord'))??
print(np.linalg.norm(m, 'fro'))
w, v = np.linalg.eig(m)
print(w)
print(np.matrix.transpose(m))

-34295.7605741
100.240247589
6.94627231646 12.8523406306
101.767256634
[ 101.13942701+0.j           -1.68400202+2.32545455j
   -1.68400202-2.32545455j    0.83909912+2.26830563j
    0.83909912-2.26830563j    2.85739498+0.j            1.86135119+0.j
   -2.29131860+0.j           -1.12291210+0.j           -0.51388907+0.j        ]
[[  8.85346116   9.97168899   9.92003936  10.23030984  10.32088641
    9.41246986   9.53803689   9.74265933  10.04140317   9.40532347]
 [  9.48674614  11.12498286   9.78441603  11.74000156  11.35676315
    9.60319765   9.18448295   9.70785707   9.56391053  10.94027123]
 [  9.81286905  11.2186394    9.45614764  10.28584111  10.15666333
   12.85234063   8.90992595  10.57304157  11.46972115   8.39044486]
 [ 10.03442888  10.0056028   10.46627307  11.58978276   9.54425749
    8.67796484   9.59040287   8.11635162  10.2040192   11.00292776]
 [ 10.82529024   9.80195778  11.2918522   10.53076359   9.92038448
   10.68365227  10.19660687  10.74289119   9.77920122  12.3121494

## Часть 3: Pandas

#### Ответьте на вопросы о данных по авиарейсам в США за январь-апрель 2008 года.

Данные: http://stat-computing.org/dataexpo/2009/2008.csv.bz2
(обратите внимание, что распаковывать этот файл не обязательно — функция `pandas.read_csv` умеет читать из архивов автоматически)

Описание: http://stat-computing.org/dataexpo/2009/the-data.html

1. Какая из причин отмены рейса (`CancellationCode`) была самой частой? (расшифровки кодов можно найти в описании данных)
2. Найдите среднее, минимальное и максимальное расстояние, пройденное самолетом.
3. Не выглядит ли подозрительным минимальное пройденное расстояние? В какие дни и на каких рейсах оно было? Какое расстояние было пройдено этими же рейсами в другие дни?
4. Из какого аэропорта было произведено больше всего вылетов? В каком городе он находится?
5. Найдите для каждого аэропорта среднее время полета (`AirTime`) по всем вылетевшим из него рейсам. Какой аэропорт имеет наибольшее значение этого показателя?
6. Найдите аэропорт, у которого наибольшая доля задержанных (`DepDelay > 0`) рейсов. Исключите при этом из рассмотрения аэропорты, из которых было отправлено меньше 1000 рейсов (используйте функцию `filter` после `groupby`).

In [19]:
import pandas

data = pandas.read_csv("2008.csv.bz2") # http://stat-computing.org/dataexpo/2009/2008.csv.bz2

##### 1 Какая из причин отмены рейса (`CancellationCode`) была самой частой? (расшифровки кодов можно найти в описании данных)

reason for cancellation (A = carrier, B = weather, C = NAS, D = security)



In [20]:
data['CancellationCode'].value_counts().keys()[0]

'B'

##### 2 Найдите среднее, минимальное и максимальное расстояние, пройденное самолетом.


In [21]:
distance = data['Distance']
mean_dist = np.mean(distance)
min_dist = np.amin(distance)
max_dist = np.amax(distance)
print(mean_dist, min_dist, max_dist)

726.387029425 11 4962


##### 3. Не выглядит ли подозрительным минимальное пройденное расстояние? В какие дни и на каких рейсах оно было? Какое расстояние было пройдено этими же рейсами в другие дни?

Коллеги, обратите внимание на третий пункт задания по Pandas. Там в том числе нужно посчитать расстояние, пройденное этими же рейсами в другие дни. Рейс характеризуется двумя величинами: номером и кодом авиакомпании. Например, SU9 — это рейс Аэрофлота номер 9, который летит из Питера в Москву. Совпадения по номеру недостаточно. Так, рейс AA9 — это рейс American Airlines номер 9 из Нью-Йорка в Сан-Франциско.

Тем, кто уже прислал мне решение, но у кого я еще не проверил — пожалуйста, сэкономьте мое время, проверьте у себя этот пункт и пришлите исправленную версию, если там есть ошибка.

In [22]:
data_with_min_dist = data.loc[data['Distance'] == min_dist]
for index, row in data_with_min_dist.iterrows():
    print("%s.%s.%s - %s%s" % (row['DayofMonth'],
                               row['Month'],
                               row['Year'],
                               row['UniqueCarrier'],
                               row['FlightNum']))

    flight_data = data.loc[(data['UniqueCarrier'] == row['UniqueCarrier']) & 
                           (data['FlightNum'] == row['FlightNum'])]
    
    flight_data = flight_data.loc[flight_data['Distance'] != min_dist]
    
#     print(flight_data[['Distance', 'DayofMonth', 'Month', 'Year', 'Origin', 'Dest']])
    print("В какие месяца:\n", sorted(flight_data['Month'].value_counts().keys()))
    print("На какие расстояния:\n", sorted(flight_data['Distance'].value_counts().keys()))
    print("\n\n")

15.5.2008 - OH4988
В какие месяца:
 [1, 2, 3, 4, 5]
На какие расстояния:
 [96, 834]



10.8.2008 - OH5572
В какие месяца:
 [1, 2, 3, 4, 5, 6, 7, 8]
На какие расстояния:
 [544]





##### 4. Из какого аэропорта было произведено больше всего вылетов? В каком городе он находится?


In [23]:
airports = pandas.read_csv("airports.csv") # http://stat-computing.org/dataexpo/2009/airports.csv

def get_airport_name(iata):
    airport = airports.loc[airports['iata'] == iata]
    return airport['airport'].values[0]

iata_of_most_loaded_airport = data['Origin'].value_counts().keys()[0]
print(iata_of_most_loaded_airport)

print(get_airport_name(iata_of_most_loaded_airport))

ATL
William B Hartsfield-Atlanta Intl


##### 5. Найдите для каждого аэропорта среднее время полета (`AirTime`) по всем вылетевшим из него рейсам. Какой аэропорт имеет наибольшее значение этого показателя?


In [24]:
g = data.groupby(['Origin'])
means = g['AirTime'].mean().order(ascending=False)
iata = (means).index.values[0]
print(iata)
print(get_airport_name(iata))

SJU
Luis Munoz Marin International


##### 6. Найдите аэропорт, у которого наибольшая доля задержанных (`DepDelay > 0`) рейсов. Исключите при этом из рассмотрения аэропорты, из которых было отправлено меньше 1000 рейсов (используйте функцию `filter` после `groupby`).

In [25]:
g = data.groupby('Origin').filter(lambda x: len(x) >= 1000)
g = g.groupby('Origin')
means = g['DepDelay'].mean()


In [26]:
iata = (means.order(ascending=False).iloc[[0]]).index.values[0]
print(iata)
print(get_airport_name(iata))

CEC
Jack McNamara 
