# Лабораторная работа 1. Язык Python, основные библиотеки для анализа данных.

ФИО: Копин Борис Александрович

Группа: 

In [2]:
import numpy as np
import pandas as pd
from functools import reduce

## Часть 1: Python

#### 1. Напишите код, который сформирует список всех натуральных чисел, не превосходящих 100, которые делятся на 7 и не делятся на 5. Нельзя использовать циклы — выполните это задание с помощью list comprehension.

In [3]:
[x for x in range(1, 101) if (x%7==0) and (x%5!=0)]

[7, 14, 21, 28, 42, 49, 56, 63, 77, 84, 91, 98]

#### 2. Напишите функцию `sort_tokens(s)`, которая принимает на вход строку, разделяет ее на токены по запятым, сортирует токены с помощью функции `sorted()` и снова соединяет их в одну строку через запятые. Например, для строки `u"ночь,фонарь,улица"` функция должна выдать `u"ночь,улица,фонарь"`. Придумайте несколько входных строк и протестируйте функцию на них.

Обратите внимание, что склеить строки можно с помощью конструкции `'x'.join(...)`. Например:

In [4]:
'! '.join(['i', 'am', 'very', 'excited', ':-)'])

'i! am! very! excited! :-)'

In [5]:
def sort_tokens(s):
    words = s.split(',')
    words = sorted(words)
    return ','.join(words)

str = u"ночь,фонарь,улица"
print(sort_tokens(str))

ночь,улица,фонарь


#### 3. Напишите функцию `remove_duplicates(a)`, которая принимает на вход список и возвращает его же, но без дубликатов и в отсортированном виде. Например, для списка `[u"ночь", u"улица", u"фонарь", u"аптека", u"аптека", u"улица", u"фонарь"]` результат должен быть `[u"аптека", u"ночь", u"улица", u"фонарь", ]`.

Подсказка: обратите внимание на структуру `set`!

In [6]:
def remove_duplicates(a):
    return set(a)
array = [u"ночь", u"улица", u"фонарь", u"аптека", u"аптека", u"улица", u"фонарь"]
print(remove_duplicates(array))

{'фонарь', 'ночь', 'улица', 'аптека'}


#### 4. Напишите функцию `word_counts(texts)`, которая принимает на вход список строк, и печатает пары (слово, число вхождений). Считайте, что слова в текстах могут быть разделены только пробелами. Например, для входа `[u'ночь улица фонарь аптека', u'аптека улица фонарь']` должно быть напечатано
>аптека 2

>улица 2

>фонарь 2

>ночь 1

Подсказки:

Чтобы разбить каждый из текстов на слова, воспользуйтесь функцией `map`, которая применяет заданную функцию к каждому элементу списка. Например, если бы нужно было каждый из текстов привести к нижнему регистру, то команда выглядела бы так:

In [7]:
list(map(lambda x: x.lower(), ["abCDefg", "HIjkL"]))

['abcdefg', 'hijkl']

После первого шага вы получите список, состоящий из списков слов. Чтобы объединить их в один список слов, воспользуйтесь функцией `reduce`. Например, просуммировать числа из списка с ее помощью можно так:



In [8]:
reduce(lambda x, y: x + y, [1, 2, 3, 4, 5])

15

Для подсчета количества вхождений слов воспользуйтесь структурой `defaultdict` из модуля `collections`. В отличие от обычного `dict`, она не генерирует ошибку при обращении к несуществущему ключу, а создает новую запись, инициализируемую нулевым значением. Например:

In [9]:
from collections import defaultdict
d = defaultdict(int)
print(d)
d['abc'] += 1
print(d)
d['xxx']
print(d)

defaultdict(<class 'int'>, {})
defaultdict(<class 'int'>, {'abc': 1})
defaultdict(<class 'int'>, {'xxx': 0, 'abc': 1})


In [10]:
def word_counts(texts):
    bag = defaultdict(int)
    
    splited = map(lambda x: x.split(' '), texts)
    reduced = reduce(lambda x, y: x + y, splited)
    
    for word in reduced:
        bag[word]+=1
        
    return bag

str = [u'ночь улица фонарь аптека', u'аптека улица фонарь']
print(word_counts(str))

defaultdict(<class 'int'>, {'фонарь': 2, 'ночь': 1, 'улица': 2, 'аптека': 2})


#### 5. (бонусное задание) Скачайте английский перевод "Преступления и наказания". Найдите 20 самых популярных слов и 20 слов, которые встречаются только один раз.

Приведите текст к нижнему регистру. Разделите текст на слова, считая разделителями все, кроме букв. Обратите внимание на функцию `split` из модуля `re`.

Не забудьте удалить пустые слова:
```
words = filter(lambda x: len(x) > 0, words)
```

In [11]:
from urllib.request import urlopen
url = "http://www.gutenberg.org/files/2554/2554.txt"
response = urlopen(url)
raw_text = response.read().decode('utf8')

In [12]:
raw_text[1000:1100]

'r five\r\nchildren in only two rooms. The father and mother spent their evenings\r\nin reading aloud to '

In [13]:
import string
import re
import operator

raw_text = raw_text.lower()
delimiters = set(raw_text) - set(string.ascii_lowercase)

words = re.split('\W+', raw_text)
words = filter(lambda x: len(x) > 0, words)

counted_words = word_counts([" ".join(words)])
sorted_words = sorted(counted_words.items(), key=operator.itemgetter(1), reverse=True)

twenty_of_most_popular_words = sorted_words[:20]
twenty_of_once_occured_words = [x for x in sorted_words if x[1] == 1][:20]

print(twenty_of_most_popular_words)
print(twenty_of_once_occured_words)

[('the', 7995), ('and', 7042), ('to', 5493), ('he', 4892), ('a', 4665), ('i', 4402), ('you', 4114), ('of', 3926), ('it', 3460), ('that', 3294), ('in', 3250), ('was', 2826), ('his', 2114), ('at', 2082), ('her', 1828), ('but', 1801), ('not', 1774), ('s', 1765), ('with', 1757), ('she', 1692)]
[('ours', 1), ('headdress', 1), ('responsive', 1), ('fervent', 1), ('ticking', 1), ('cuckoo', 1), ('rusty', 1), ('governorship', 1), ('trustful', 1), ('ensuring', 1), ('dost', 1), ('trousseau', 1), ('diamond', 1), ('posed', 1), ('propose', 1), ('hugging', 1), ('abyss', 1), ('subdue', 1), ('seconded', 1), ('verbal', 1)]


## Часть 2: NumPy и SciPy

#### 1. Повторите 1000 раз следующий эксперимент: сгенерируйте две матрицы размера $10 \times 10$ из стандартного нормального распределения, перемножьте их (как матрицы) и найдите максимальный элемент. Какое среднее значение по экспериментам у максимальных элементов? 95-процентная квантиль?

Для вычисления квантили воспользуйтесь функцией `np.percentile`

In [14]:
iterations = 1000
alpha = 95

maximums = []
for x in range(iterations):
    matrix1 = np.random.standard_normal(size=(10,10))
    matrix2 = np.random.standard_normal(size=(10,10))
    maximums.append(np.max(np.dot(matrix1, matrix2)))
    
print(np.mean(maximums))
print(np.percentile(maximums, alpha))

8.39036667341
11.8388818848


#### 2. Сгенерируйте 1000 чисел из распределения Пуассона с параметром $\lambda = 5$. Сформируйте массив, в котором в i-м элементе будет записано количество сгенерированных чисел, равных i.

Обратите внимание на функцию `np.bincount`

In [15]:
n = np.random.poisson(5, 1000)

counts = np.bincount(n)
indexes = np.nonzero(counts)[0]
bag = list(zip(range(counts.size), counts))

print(bag)
print(counts)


[(0, 10), (1, 24), (2, 80), (3, 134), (4, 184), (5, 156), (6, 158), (7, 94), (8, 88), (9, 43), (10, 19), (11, 4), (12, 3), (13, 0), (14, 1), (15, 1), (16, 0), (17, 1)]
[ 10  24  80 134 184 156 158  94  88  43  19   4   3   0   1   1   0   1]


#### 3. Реализуйте функцию, которая принимает на вход numpy-массив целых чисел `a`, и генерирует массив, в котором число `i` встречается `a[i]` раз. Протестируйте на результате из прошлого задания.

Обратите внимание на функцию `np.repeat`

In [16]:
def repeater(a):
    return np.repeat(range(len(a)), a)

print(repeater(counts))

[ 0  0  0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2
  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2
  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2
  2  2  2  2  2  2  2  2  2  2  2  2  2  2  3  3  3  3  3  3  3  3  3  3  3
  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3
  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3
  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3
  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3
  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  4  4
  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4
  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4
  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4
  4  4  4  4

#### 4. Напишите функцию `scale(X)`, которая принимает на вход матрицу и масштабирует каждый ее столбец (вычитает среднее и делит на стандартное отклонение). Убедитесь, что в функции не будет происходить деления на ноль. Протестируйте на каких-нибудь данных.

In [17]:
def scale(x):
    mean_vect = np.mean(x, axis=0)
    std_vect = np.std(x, axis=0)
    return ((x.T - mean_vect) / std_vect).T

myarr = np.random.binomial(100, 0.7, size=(10, 10))

print(myarr)
myarr = scale(myarr)
print(myarr)


[[69 69 70 72 72 66 64 69 69 59]
 [69 72 73 61 75 72 71 73 71 69]
 [69 75 76 69 69 80 67 76 70 72]
 [79 65 71 76 65 69 72 64 62 72]
 [77 75 69 60 66 71 68 74 75 68]
 [63 68 70 72 70 69 67 70 67 68]
 [67 68 69 70 72 71 68 65 69 78]
 [66 65 65 69 69 69 63 72 74 72]
 [62 72 73 74 67 76 75 73 70 74]
 [66 64 70 68 76 70 73 73 75 66]]
[[ 0.05772434  0.05772434  0.2501388   0.63496772  0.63496772 -0.51951904
  -0.90434797  0.05772434  0.05772434 -1.86642027]
 [-0.07795496  0.7015946   0.96144445 -2.15675376  1.48114415  0.7015946
   0.44174475  0.96144445  0.44174475 -0.07795496]
 [-0.57142857  1.57142857  1.92857143 -0.57142857 -0.57142857  3.35714286
  -1.28571429  1.92857143 -0.21428571  0.5       ]
 [ 2.02547608 -0.83883353  0.38872773  1.41169545 -0.83883353 -0.02045935
   0.59332128 -1.04342707 -1.45261416  0.59332128]
 [ 1.98443071  1.40923341 -0.31635852 -2.90474641 -1.17915448  0.25883879
  -0.60395717  1.12163475  1.40923341 -0.60395717]
 [-2.18648298 -0.86932456 -0.34246119  0.1844

#### 5. Сгенерируйте матрицу с элементами из нормального распределения $\mathcal{N}(10, 1)$. Найдите ее:
- определитель
- след
- наименьший и наибольший элементы
- спектральную норму
- норму Фробениуса
- собственные числа
- обратную матрицу

In [18]:
m = np.random.normal(10, 1, size=(10, 10))

print(u"определитель = ", np.linalg.det(m))
print(u"след = ", np.trace(m))
print(u"наименьший и наибольший элемент = ", np.amin(m), np.amax(m))
print(u"спектральная норма = ", np.linalg.norm(m, 2))
print(u"норма Фробениуса = ", np.linalg.norm(m, 'fro'))
w, v = np.linalg.eig(m)
print(u"собственные числа = ", w)
print(u"обратная матрица = ", np.linalg.inv(m))

определитель =  51736.4972712
след =  101.05410441
наименьший и наибольший элемент =  7.89824570527 12.6272865463
спектральная норма =  100.415160658
норма Фробениуса =  100.878201555
собственные числа =  [ 100.38308224+0.j            3.22317462+0.j           -0.63006305+2.95630629j
   -0.63006305-2.95630629j    1.52757297+2.2465405j
    1.52757297-2.2465405j    -2.19604522+0.j           -0.69727685+0.97006022j
   -0.69727685-0.97006022j   -0.75657336+0.j        ]
обратная матрица =  [[ 0.02116813 -0.07999608  0.19968587  0.23602449 -0.2180217   0.08695621
   0.13270666 -0.29993353  0.05675942 -0.14536658]
 [ 0.33338587 -0.33682738  1.45099699 -0.7057799  -0.94500177  0.19713155
   0.21685068  0.36805073 -0.69906329  0.07385449]
 [-0.47868632  0.23510408 -1.19556482  0.2545994   0.61267508 -0.17173353
  -0.06315683  0.11145979  0.5209013   0.24718668]
 [ 0.27857716 -0.31287775  1.70344694 -0.6963177  -0.90047543  0.27663933
   0.19702366  0.62501722 -1.00568806 -0.22107659]
 [ 0.287158

## Часть 3: Pandas

#### Ответьте на вопросы о данных по авиарейсам в США за январь-апрель 2008 года.

Данные: http://stat-computing.org/dataexpo/2009/2008.csv.bz2
(обратите внимание, что распаковывать этот файл не обязательно — функция `pandas.read_csv` умеет читать из архивов автоматически)

Описание: http://stat-computing.org/dataexpo/2009/the-data.html

1. Какая из причин отмены рейса (`CancellationCode`) была самой частой? (расшифровки кодов можно найти в описании данных)
2. Найдите среднее, минимальное и максимальное расстояние, пройденное самолетом.
3. Не выглядит ли подозрительным минимальное пройденное расстояние? В какие дни и на каких рейсах оно было? Какое расстояние было пройдено этими же рейсами в другие дни?
4. Из какого аэропорта было произведено больше всего вылетов? В каком городе он находится?
5. Найдите для каждого аэропорта среднее время полета (`AirTime`) по всем вылетевшим из него рейсам. Какой аэропорт имеет наибольшее значение этого показателя?
6. Найдите аэропорт, у которого наибольшая доля задержанных (`DepDelay > 0`) рейсов. Исключите при этом из рассмотрения аэропорты, из которых было отправлено меньше 1000 рейсов (используйте функцию `filter` после `groupby`).

In [19]:
import pandas

data = pandas.read_csv("2008.csv.bz2") # http://stat-computing.org/dataexpo/2009/2008.csv.bz2

##### 1 Какая из причин отмены рейса (`CancellationCode`) была самой частой? (расшифровки кодов можно найти в описании данных)

reason for cancellation (A = carrier, B = weather, C = NAS, D = security)



In [20]:
data['CancellationCode'].value_counts().keys()[0]

'B'

##### 2 Найдите среднее, минимальное и максимальное расстояние, пройденное самолетом.


In [21]:
distance = data['Distance']
mean_dist = np.mean(distance)
min_dist = np.amin(distance)
max_dist = np.amax(distance)
print(mean_dist, min_dist, max_dist)

726.387029425 11 4962


##### 3. Не выглядит ли подозрительным минимальное пройденное расстояние? В какие дни и на каких рейсах оно было? Какое расстояние было пройдено этими же рейсами в другие дни?

Коллеги, обратите внимание на третий пункт задания по Pandas. Там в том числе нужно посчитать расстояние, пройденное этими же рейсами в другие дни. Рейс характеризуется двумя величинами: номером и кодом авиакомпании. Например, SU9 — это рейс Аэрофлота номер 9, который летит из Питера в Москву. Совпадения по номеру недостаточно. Так, рейс AA9 — это рейс American Airlines номер 9 из Нью-Йорка в Сан-Франциско.

Тем, кто уже прислал мне решение, но у кого я еще не проверил — пожалуйста, сэкономьте мое время, проверьте у себя этот пункт и пришлите исправленную версию, если там есть ошибка.

In [22]:
data_with_min_dist = data.loc[data['Distance'] == min_dist]
for index, row in data_with_min_dist.iterrows():
    print("%s.%s.%s - %s%s" % (row['DayofMonth'],
                               row['Month'],
                               row['Year'],
                               row['UniqueCarrier'],
                               row['FlightNum']))

    flight_data = data.loc[(data['UniqueCarrier'] == row['UniqueCarrier']) & 
                           (data['FlightNum'] == row['FlightNum'])]
    
    flight_data = flight_data.loc[flight_data['Distance'] != min_dist]
    
    print("В какие месяца:\n", sorted(flight_data['Month'].value_counts().keys()))
    print("На какие расстояния:\n", sorted(flight_data['Distance'].value_counts().keys()))
    print('\n')

15.5.2008 - OH4988
В какие месяца:
 [1, 2, 3, 4, 5]
На какие расстояния:
 [96, 834]


10.8.2008 - OH5572
В какие месяца:
 [1, 2, 3, 4, 5, 6, 7, 8]
На какие расстояния:
 [544]




##### 4. Из какого аэропорта было произведено больше всего вылетов? В каком городе он находится?


In [23]:
airports = pandas.read_csv("airports.csv") # http://stat-computing.org/dataexpo/2009/airports.csv

def get_airport_name(iata):
    airport = airports.loc[airports['iata'] == iata]
    return airport['airport'].values[0]

iata_of_most_loaded_airport = data['Origin'].value_counts().keys()[0]
print(iata_of_most_loaded_airport)

print(get_airport_name(iata_of_most_loaded_airport))

ATL
William B Hartsfield-Atlanta Intl


##### 5. Найдите для каждого аэропорта среднее время полета (`AirTime`) по всем вылетевшим из него рейсам. Какой аэропорт имеет наибольшее значение этого показателя?


In [24]:
g = data.groupby(['Origin'])
means = g['AirTime'].mean().order(ascending=False)
iata = (means).index.values[0]
print(iata)
print(get_airport_name(iata))

SJU
Luis Munoz Marin International


##### 6. Найдите аэропорт, у которого наибольшая доля задержанных (`DepDelay > 0`) рейсов. Исключите при этом из рассмотрения аэропорты, из которых было отправлено меньше 1000 рейсов (используйте функцию `filter` после `groupby`).

In [25]:
data['DepDelayBin'] = data['DepDelay'] > 0

groups_by_origin = data.groupby('Origin').filter(lambda x: len(x) > 1000)
groups_by_origin = groups_by_origin.groupby('Origin')
sum_of_delayed_flights = groups_by_origin['DepDelayBin'].mean()

In [26]:
iata = (sum_of_delayed_flights.order(ascending=False).iloc[[0]]).index.values[0]
print(iata)
print(get_airport_name(iata))

DAL
Dallas Love 
