# Лабораторная работа 1. Язык Python, основные библиотеки для анализа данных.

ФИО: Копин Борис Александрович

Группа: 

In [76]:
import numpy as np
import pandas as pd
from functools import reduce

## Часть 1: Python

#### 1. Напишите код, который сформирует список всех натуральных чисел, не превосходящих 100, которые делятся на 7 и не делятся на 5. Нельзя использовать циклы — выполните это задание с помощью list comprehension.

In [77]:
[x for x in range(1, 101) if (x%7==0) and (x%5!=0)]

[7, 14, 21, 28, 42, 49, 56, 63, 77, 84, 91, 98]

#### 2. Напишите функцию `sort_tokens(s)`, которая принимает на вход строку, разделяет ее на токены по запятым, сортирует токены с помощью функции `sorted()` и снова соединяет их в одну строку через запятые. Например, для строки `u"ночь,фонарь,улица"` функция должна выдать `u"ночь,улица,фонарь"`. Придумайте несколько входных строк и протестируйте функцию на них.

Обратите внимание, что склеить строки можно с помощью конструкции `'x'.join(...)`. Например:

In [78]:
'! '.join(['i', 'am', 'very', 'excited', ':-)'])

'i! am! very! excited! :-)'

In [79]:
def sort_tokens(s):
    words = s.split(',')
    words = sorted(words)
    return ','.join(words)

str = u"ночь,фонарь,улица"
print(sort_tokens(str))

ночь,улица,фонарь


#### 3. Напишите функцию `remove_duplicates(a)`, которая принимает на вход список и возвращает его же, но без дубликатов и в отсортированном виде. Например, для списка `[u"ночь", u"улица", u"фонарь", u"аптека", u"аптека", u"улица", u"фонарь"]` результат должен быть `[u"аптека", u"ночь", u"улица", u"фонарь", ]`.

Подсказка: обратите внимание на структуру `set`!

In [80]:
def remove_duplicates(a):
    return set(a)
array = [u"ночь", u"улица", u"фонарь", u"аптека", u"аптека", u"улица", u"фонарь"]
print(remove_duplicates(array))

{'улица', 'аптека', 'фонарь', 'ночь'}


#### 4. Напишите функцию `word_counts(texts)`, которая принимает на вход список строк, и печатает пары (слово, число вхождений). Считайте, что слова в текстах могут быть разделены только пробелами. Например, для входа `[u'ночь улица фонарь аптека', u'аптека улица фонарь']` должно быть напечатано
>аптека 2

>улица 2

>фонарь 2

>ночь 1

Подсказки:

Чтобы разбить каждый из текстов на слова, воспользуйтесь функцией `map`, которая применяет заданную функцию к каждому элементу списка. Например, если бы нужно было каждый из текстов привести к нижнему регистру, то команда выглядела бы так:

In [81]:
list(map(lambda x: x.lower(), ["abCDefg", "HIjkL"]))

['abcdefg', 'hijkl']

После первого шага вы получите список, состоящий из списков слов. Чтобы объединить их в один список слов, воспользуйтесь функцией `reduce`. Например, просуммировать числа из списка с ее помощью можно так:



In [82]:
reduce(lambda x, y: x + y, [1, 2, 3, 4, 5])

15

Для подсчета количества вхождений слов воспользуйтесь структурой `defaultdict` из модуля `collections`. В отличие от обычного `dict`, она не генерирует ошибку при обращении к несуществущему ключу, а создает новую запись, инициализируемую нулевым значением. Например:

In [83]:
from collections import defaultdict
d = defaultdict(int)
print(d)
d['abc'] += 1
print(d)
d['xxx']
print(d)

defaultdict(<class 'int'>, {})
defaultdict(<class 'int'>, {'abc': 1})
defaultdict(<class 'int'>, {'abc': 1, 'xxx': 0})


In [84]:
def word_counts(texts):
    bag = defaultdict(int)
    
    splited = map(lambda x: x.split(' '), texts)
    reduced = reduce(lambda x, y: x + y, splited)
    
    for word in reduced:
        bag[word]+=1
        
    return bag

str = [u'ночь улица фонарь аптека', u'аптека улица фонарь']
print(word_counts(str))

defaultdict(<class 'int'>, {'улица': 2, 'аптека': 2, 'фонарь': 2, 'ночь': 1})


#### 5. (бонусное задание) Скачайте английский перевод "Преступления и наказания". Найдите 20 самых популярных слов и 20 слов, которые встречаются только один раз.

Приведите текст к нижнему регистру. Разделите текст на слова, считая разделителями все, кроме букв. Обратите внимание на функцию `split` из модуля `re`.

Не забудьте удалить пустые слова:
```
words = filter(lambda x: len(x) > 0, words)
```

In [85]:
from urllib.request import urlopen
url = "http://www.gutenberg.org/files/2554/2554.txt"
response = urlopen(url)
raw_text = response.read().decode('utf8')

In [86]:
raw_text[1000:1100]

'r five\r\nchildren in only two rooms. The father and mother spent their evenings\r\nin reading aloud to '

In [87]:
import string
import re
import operator

raw_text = raw_text.lower()
delimiters = set(raw_text) - set(string.ascii_lowercase)

words = re.split('\W+', raw_text)
words = filter(lambda x: len(x) > 0, words)

counted_words = word_counts([" ".join(words)])
sorted_words = sorted(counted_words.items(), key=operator.itemgetter(1), reverse=True)

twenty_of_most_popular_words = sorted_words[:20]
twenty_of_once_occured_words = [x for x in sorted_words if x[1] == 1][:20]

print(twenty_of_most_popular_words)
print(twenty_of_once_occured_words)

[('the', 7995), ('and', 7042), ('to', 5493), ('he', 4892), ('a', 4665), ('i', 4402), ('you', 4114), ('of', 3926), ('it', 3460), ('that', 3294), ('in', 3250), ('was', 2826), ('his', 2114), ('at', 2082), ('her', 1828), ('but', 1801), ('not', 1774), ('s', 1765), ('with', 1757), ('she', 1692)]
[('piping', 1), ('undergoing', 1), ('adornment', 1), ('threes', 1), ('mourners', 1), ('livingstone', 1), ('legitimate', 1), ('posed', 1), ('proofread', 1), ('inartistic', 1), ('recognition', 1), ('chinks', 1), ('superficially', 1), ('keyhole', 1), ('outlet', 1), ('abortions', 1), ('misgivings', 1), ('barrows', 1), ('gambrinus', 1), ('boldness', 1)]


## Часть 2: NumPy и SciPy

#### 1. Повторите 1000 раз следующий эксперимент: сгенерируйте две матрицы размера $10 \times 10$ из стандартного нормального распределения, перемножьте их (как матрицы) и найдите максимальный элемент. Какое среднее значение по экспериментам у максимальных элементов? 95-процентная квантиль?

Для вычисления квантили воспользуйтесь функцией `np.percentile`

In [88]:
iterations = 1000
alpha = 95

maximums = []
for x in range(iterations):
    matrix1 = np.random.standard_normal(size=(10,10))
    matrix2 = np.random.standard_normal(size=(10,10))
    maximums.append(np.max(np.dot(matrix1, matrix2)))
    
print(np.mean(maximums))
print(np.percentile(maximums, alpha))

8.45238253829
11.9015806231


#### 2. Сгенерируйте 1000 чисел из распределения Пуассона с параметром $\lambda = 5$. Сформируйте массив, в котором в i-м элементе будет записано количество сгенерированных чисел, равных i.

Обратите внимание на функцию `np.bincount`

In [89]:
n = np.random.poisson(5, 1000)

counts = np.bincount(n)
indexes = np.nonzero(counts)[0]
bag = list(zip(range(counts.size), counts))

print(bag)
print(counts)


[(0, 7), (1, 33), (2, 78), (3, 137), (4, 164), (5, 203), (6, 150), (7, 101), (8, 68), (9, 26), (10, 25), (11, 6), (12, 1), (13, 1)]
[  7  33  78 137 164 203 150 101  68  26  25   6   1   1]


#### 3. Реализуйте функцию, которая принимает на вход numpy-массив целых чисел `a`, и генерирует массив, в котором число `i` встречается `a[i]` раз. Протестируйте на результате из прошлого задания.

Обратите внимание на функцию `np.repeat`

In [90]:
def repeater(a):
    return np.repeat(range(len(a)), a)

print(repeater(counts))

[ 0  0  0  0  0  0  0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  2  2  2  2  2  2  2  2  2
  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2
  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2
  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  3  3  3  3  3  3  3
  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3
  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3
  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3
  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3
  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3
  3  3  3  3  3  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4
  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4
  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4
  4  4  4  4

#### 4. Напишите функцию `scale(X)`, которая принимает на вход матрицу и масштабирует каждый ее столбец (вычитает среднее и делит на стандартное отклонение). Убедитесь, что в функции не будет происходить деления на ноль. Протестируйте на каких-нибудь данных.

In [91]:
def scale(x):
    mean_vect = np.mean(x, axis=0)
    std_vect = np.std(x, axis=0)
    return ((x.T - mean_vect) / std_vect).T

myarr = np.random.binomial(100, 0.7, size=(10, 10))

print(myarr)
myarr = scale(myarr)
print(myarr)


[[69 66 73 70 76 69 73 79 70 75]
 [62 72 65 71 66 68 74 63 64 66]
 [66 71 76 71 73 67 61 68 75 73]
 [75 75 66 74 66 81 72 69 70 69]
 [79 63 70 72 70 68 72 61 73 71]
 [67 77 66 81 72 73 64 66 63 72]
 [68 71 72 65 71 69 73 73 73 67]
 [64 66 71 69 73 77 67 71 69 72]
 [68 74 67 73 77 70 65 67 67 66]
 [65 64 61 71 71 66 76 71 72 70]]
[[ 0.1440622  -0.47334723  0.96727478  0.34986535  1.58468421  0.1440622
   0.96727478  2.20209365  0.34986535  1.37888107]
 [-1.71213995  0.45512581 -1.06196022  0.23839923 -0.84523365 -0.41178049
   0.88857896 -1.49541337 -1.2786868  -0.84523365]
 [-0.6362194   0.54196467  1.72014875  0.54196467  1.0132383  -0.40058259
  -1.81440347 -0.16494577  1.48451193  1.0132383 ]
 [ 0.85177246  0.85177246 -1.47124334  0.59365959 -1.47124334  2.40044966
   0.07743386 -0.69690474 -0.43879187 -0.69690474]
 [ 2.17872335 -2.4692198  -0.43574467  0.14524822 -0.43574467 -1.01673756
   0.14524822 -3.05021269  0.43574467 -0.14524822]
 [-0.83400743  1.36074897 -1.05348308  2.2386

#### 5. Сгенерируйте матрицу с элементами из нормального распределения $\mathcal{N}(10, 1)$. Найдите ее:
- определитель
- след
- наименьший и наибольший элементы
- спектральную норму
- норму Фробениуса
- собственные числа
- обратную матрицу

In [92]:
m = np.random.normal(10, 1, size=(10, 10))

print(u"определитель = ", np.linalg.det(m))
print(u"след = ", np.trace(m))
print(u"наименьший и наибольший элемент = ", np.amin(m), np.amax(m))
print(u"спектральная норма = ", np.linalg.norm(m, 2))
print(u"норма Фробениуса = ", np.linalg.norm(m, 'fro'))
w, v = np.linalg.eig(m)
print(u"собственные числа = ", w)
print(u"обратная матрица = ", np.linalg.inv(m))

определитель =  14592.9555831
след =  99.7688090907
наименьший и наибольший элемент =  7.44916006786 12.2945592635
спектральная норма =  100.653325509
норма Фробениуса =  101.071151632
собственные числа =  [ 100.61998337+0.j            0.91025154+2.50775416j
    0.91025154-2.50775416j    1.52523235+0.j            1.26055792+0.95977125j
    1.26055792-0.95977125j   -2.31248415+0.77035429j
   -2.31248415-0.77035429j   -0.60002384+0.j           -1.49303341+0.j        ]
обратная матрица =  [[ 0.57375599 -0.31200366 -0.23424536 -0.0859683   0.02538316 -0.21156987
   0.03352646  0.18999817  0.06660301 -0.0243757 ]
 [-0.0893712   0.65391816 -0.07769867 -0.95058749  0.25226127 -0.34378446
  -0.16742699  0.33847291  0.18751348  0.25891875]
 [-0.75843689 -0.32351199 -0.61334761  1.46696751 -0.25331074  0.98218203
   0.1041704   0.04122848 -0.14043444 -0.56901772]
 [ 0.45177366  0.52643154  0.3994386  -1.39646246  0.57065398 -0.75436946
  -0.09315987  0.03964899 -0.05321603  0.40403404]
 [-0.8939

## Часть 3: Pandas

#### Ответьте на вопросы о данных по авиарейсам в США за январь-апрель 2008 года.

Данные: http://stat-computing.org/dataexpo/2009/2008.csv.bz2
(обратите внимание, что распаковывать этот файл не обязательно — функция `pandas.read_csv` умеет читать из архивов автоматически)

Описание: http://stat-computing.org/dataexpo/2009/the-data.html

1. Какая из причин отмены рейса (`CancellationCode`) была самой частой? (расшифровки кодов можно найти в описании данных)
2. Найдите среднее, минимальное и максимальное расстояние, пройденное самолетом.
3. Не выглядит ли подозрительным минимальное пройденное расстояние? В какие дни и на каких рейсах оно было? Какое расстояние было пройдено этими же рейсами в другие дни?
4. Из какого аэропорта было произведено больше всего вылетов? В каком городе он находится?
5. Найдите для каждого аэропорта среднее время полета (`AirTime`) по всем вылетевшим из него рейсам. Какой аэропорт имеет наибольшее значение этого показателя?
6. Найдите аэропорт, у которого наибольшая доля задержанных (`DepDelay > 0`) рейсов. Исключите при этом из рассмотрения аэропорты, из которых было отправлено меньше 1000 рейсов (используйте функцию `filter` после `groupby`).

In [93]:
import pandas

data = pandas.read_csv("2008.csv.bz2") # http://stat-computing.org/dataexpo/2009/2008.csv.bz2

##### 1 Какая из причин отмены рейса (`CancellationCode`) была самой частой? (расшифровки кодов можно найти в описании данных)

reason for cancellation (A = carrier, B = weather, C = NAS, D = security)



In [94]:
data['CancellationCode'].value_counts().keys()[0]

'B'

##### 2 Найдите среднее, минимальное и максимальное расстояние, пройденное самолетом.


In [95]:
distance = data['Distance']
mean_dist = np.mean(distance)
min_dist = np.amin(distance)
max_dist = np.amax(distance)
print(mean_dist, min_dist, max_dist)

726.387029425 11 4962


##### 3. Не выглядит ли подозрительным минимальное пройденное расстояние? В какие дни и на каких рейсах оно было? Какое расстояние было пройдено этими же рейсами в другие дни?

Коллеги, обратите внимание на третий пункт задания по Pandas. Там в том числе нужно посчитать расстояние, пройденное этими же рейсами в другие дни. Рейс характеризуется двумя величинами: номером и кодом авиакомпании. Например, SU9 — это рейс Аэрофлота номер 9, который летит из Питера в Москву. Совпадения по номеру недостаточно. Так, рейс AA9 — это рейс American Airlines номер 9 из Нью-Йорка в Сан-Франциско.

Тем, кто уже прислал мне решение, но у кого я еще не проверил — пожалуйста, сэкономьте мое время, проверьте у себя этот пункт и пришлите исправленную версию, если там есть ошибка.

In [102]:
data_with_min_dist = data.loc[data['Distance'] == min_dist]
for index, row in data_with_min_dist.iterrows():
    print("%s.%s.%s - %s%s" % (row['DayofMonth'],
                               row['Month'],
                               row['Year'],
                               row['UniqueCarrier'],
                               row['FlightNum']))

    flight_data = data.loc[(data['UniqueCarrier'] == row['UniqueCarrier']) & 
                           (data['FlightNum'] == row['FlightNum'])]
    
    flight_data = flight_data.loc[flight_data['Distance'] != min_dist]
    
    print("В какие месяца:\n", sorted(flight_data['Month'].value_counts().keys()))
    print("На какие расстояния:\n", sorted(flight_data['Distance'].value_counts().keys()))
    print('\n')

15.5.2008 - OH4988
В какие месяца:
 [1, 2, 3, 4, 5]
На какие расстояния:
 [96, 834]


10.8.2008 - OH5572
В какие месяца:
 [1, 2, 3, 4, 5, 6, 7, 8]
На какие расстояния:
 [544]




##### 4. Из какого аэропорта было произведено больше всего вылетов? В каком городе он находится?


In [97]:
airports = pandas.read_csv("airports.csv") # http://stat-computing.org/dataexpo/2009/airports.csv

def get_airport_name(iata):
    airport = airports.loc[airports['iata'] == iata]
    return airport['airport'].values[0]

iata_of_most_loaded_airport = data['Origin'].value_counts().keys()[0]
print(iata_of_most_loaded_airport)

print(get_airport_name(iata_of_most_loaded_airport))

ATL
William B Hartsfield-Atlanta Intl


##### 5. Найдите для каждого аэропорта среднее время полета (`AirTime`) по всем вылетевшим из него рейсам. Какой аэропорт имеет наибольшее значение этого показателя?


In [98]:
g = data.groupby(['Origin'])
means = g['AirTime'].mean().order(ascending=False)
iata = (means).index.values[0]
print(iata)
print(get_airport_name(iata))

SJU
Luis Munoz Marin International


##### 6. Найдите аэропорт, у которого наибольшая доля задержанных (`DepDelay > 0`) рейсов. Исключите при этом из рассмотрения аэропорты, из которых было отправлено меньше 1000 рейсов (используйте функцию `filter` после `groupby`).

In [104]:
data['DepDelayBin'] = data['DepDelay'] > 0

groups_by_origin = data.groupby('Origin').filter(lambda x: len(x) > 1000)
groups_by_origin = groups_by_origin.groupby('Origin')
sum_of_delayed_flights = groups_by_origin['DepDelayBin'].sum()

In [105]:
iata = (sum_of_delayed_flights.order(ascending=False).iloc[[0]]).index.values[0]
print(iata)
print(get_airport_name(iata))

ATL
William B Hartsfield-Atlanta Intl
